blogMe/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

blogMe/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogMe/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

blogMe/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :user_posts
  has_many :users, through: :user_posts

  belongs_to :creator, class_name: 'User'

  validates :title, :body, presence: true
end

blogMe/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_posts
  has_many :comments
  has_many :created_posts, class_name: 'Post', foreign_key: :creator_id

  validates :username, :email, presence: true, uniqueness: true
end

blogMe/app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

blogMe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blogMe/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def create
    @post = current_user.created_posts.create(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      @errors = @post.errors.full_messages
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.creator == current_user
      if @post.update_attributes(post_params)
        flash[:notice] = "Post Updated"
      end
    else
      @errors = @post.errors.full_messages
      flash[:notice] = "Post not updated..."
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :creator_id)
  end



end

blogMe/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.find_by(email: params[:email])
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

blogMe/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.user_id
      redirect_to user_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @created_posts = current_user.created_posts
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

blogMe/app/helpers/application_helper.rb
module ApplicationHelper
end

blogMe/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in.' if current_user.nil?
  end

  def logged_in?
    !!current_user
  end

end

blogMe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-container">
      <div class="home-container">
        <%= link_to 'BlogMe', root_path %>
      </div>
      <div class="account-container">
        <% if logged_in? %>
          <%= link_to 'Profile', user_path(current_user) %>
          <%= link_to 'Logout', sessions_path(current_user) %>
          <% else %>
          <%= link_to 'Login', new_session_path %>
          <%= link_to 'Create Account', new_user_path %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

blogMe/app/views/posts/index.html.erb
<h1>Post#index</h1>
<p class="greeting">Welcome to BlogMe! Get those thoughts out of your head and into the world.</p>

<ul class="post-container">
  <%= @posts.each do |post| %>
  <li class="post-card"><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

blogMe/app/views/users/_creator.html.erb
<div class="profile-list">
  <h3>Your Posts:</h3>
  <% current_user.created_posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>


</div>

blogMe/app/views/users/_reader.html.erb
<div class="read-post-list">
  <h3><%= @user.username %>'s Posts:</h3>
  <% @user.created_posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
</div>

blogMe/app/views/users/new.html.erb
<h2>Create Your Account</h2>
 <%= form_with model: @user do |f| %>
 <div>

 <%= f.label :username %>
 <%= f.text_field :username, autofocus: true %>
 </div>
 <div>

 <%= f.label :email %>
 <%= f.text_field :email %>
 </div>
 <div>

 <%= f.label :password %>
 <%= f.text_field :password %>
 </div>
 <%= f.submit "Create Account" %>
 <% end %>

blogMe/app/views/users/show.html.erb
<h3>Hello <%= current_user.username %>!</h3>
<% if @user != current_user %>
  <%= render partial: 'reader' %>
<% end %>

<% if @user == current_user %>
  <%= render partial: 'creator' %>
<% end %>